-- 코드를 입력하세요
SELECT C.CAR_ID, C.CAR_TYPE, (C.DAILY_FEE * 30 * ((100 - P.DISCOUNT_RATE) / 100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON C.CAR_ID = H.CAR_ID AND H.END_DATE >= TO_DATE('20221101', 'YYYYMMDD') AND H.START_DATE <= TO_DATE('20221130', 'YYYYMMDD')
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON C.CAR_TYPE = P.CAR_TYPE AND P.DURATION_TYPE = '30일 이상'
WHERE C.CAR_TYPE IN ('세단', 'SUV') 
AND H.CAR_ID IS NULL
AND (C.DAILY_FEE * 30 * ((100 - P.DISCOUNT_RATE) / 100)) BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC;