-- 코드를 입력하세요
SELECT TO_CHAR(S.SALES_DATE, 'YYYY') AS YEAR, TO_NUMBER(TO_CHAR(S.SALES_DATE, 'MM')) AS MONTH,
U.GENDER, COUNT(DISTINCT U.USER_ID) AS USERS FROM USER_INFO U JOIN ONLINE_SALE S
ON U.USER_ID = S.USER_ID
GROUP BY TO_CHAR(S.SALES_DATE, 'YYYY'), TO_CHAR(S.SALES_DATE, 'MM'), U.GENDER
HAVING U.GENDER IS NOT NULL
ORDER BY 1, 2, 3;